In [15]:
import numpy as np
import pandas as pd
import os

pathdata = '/mydata/watres/quentin/code/FLOW/data/GISID2hourly_data_withPET/'
all_GISID = np.array([el[:-4] for el in os.listdir(pathdata)])
all_GISID = np.array([el for el in all_GISID if not('ipynb_checkpo' in el)])

GISID = all_GISID[0]
df = pd.read_csv('/mydata/watres/quentin/code/FLOW/data/GISID2hourly_data_withPET/{0}.csv'.format(GISID), sep=',')
df

,discharge,precip,t,datetime,tmin,tmax,tabs,pet
0,0.219167,0.046603,2005.000000,2005-01-01 00:00:00,1.658938,7.095829,3.673320,0.435224
1,0.210833,0.000033,2005.000114,2005-01-01 01:00:00,1.658938,7.095829,3.673320,0.435224
2,0.206833,0.056963,2005.000228,2005-01-01 02:00:00,1.658938,7.095829,3.673320,0.435224
3,0.208500,0.034366,2005.000342,2005-01-01 03:00:00,1.658938,7.095829,3.673320,0.435224
4,0.210500,0.011202,2005.000457,2005-01-01 04:00:00,1.658938,7.095829,3.673320,0.435224
...,...,...,...,...,...,...,...,...
140228,0.202000,0.000000,2020.996812,2020-12-30 20:00:00,-0.239202,3.591478,1.395561,0.324806
140229,0.201500,0.000000,2020.996926,2020-12-30 21:00:00,-0.239202,3.591478,1.395561,0.324806
140230,0.201000,0.000000,2020.997040,2020-12-30 22:00:00,-0.239202,3.591478,1.395561,0.324806
140231,0.200167,0.000000,2020.997154,2020-12-30 23:00:00,-0.239202,3.591478,1.395561,0.324806
140232,0.198000,0.000000,2020.997268,2020-12-31 00:00:00,-1.643662,3.610236,0.974141,0.374058

In [14]:
for GISID in all_GISID:
    df = pd.read_csv('/mydata/watres/quentin/code/FLOW/data/GISID2hourly_data_withPET/{0}.csv'.format(GISID), sep=',')
    df = df.rename(columns={"discharge": "q"})
    df = df.rename(columns={"t": "timeyear"})
    df = df.rename(columns={"datetime": "date"})
    df = df.rename(columns={"precip": "p"})
    df = df.fillna(0)
    df = df.loc[df['timeyear']>2014]
    df = df.reset_index()
    import os
    directory = '/mydata/watres/quentin/code/FLOW/hourly_analysis/RES_GAMCR/real_data/{0}/'.format(GISID)
    if not os.path.exists(directory):
        os.makedirs(directory)
    df.to_csv(directory+'data_{0}.txt'.format(GISID), index=False)

In [29]:
for GISID in all_GISID:
    try:
        directory = '/mydata/watres/quentin/code/FLOW/hourly_analysis/RES_GAMCR/real_data/{0}/'.format(GISID)
        df = pd.read_csv(directory+'data_{0}.txt'.format(GISID))
        df['date'] = pd.to_datetime(df['date'])
        
        # Compute the difference between consecutive dates
        date_diffs = df['date'].diff()
        
        # Find the maximum difference
        max_diff = date_diffs.max()
        print(GISID, max_diff)
    except:
        pass

325 0 days 01:00:00
167 0 days 01:00:00
69 0 days 01:00:00
98 0 days 01:00:00
187 0 days 01:00:00
164 0 days 01:00:00
252 0 days 01:00:00
14 0 days 01:00:00
156 0 days 01:00:00
27 0 days 01:00:00
192 0 days 01:00:00
99 0 days 01:00:00
191 0 days 01:00:00
173 0 days 01:00:00
113 0 days 01:00:00
233 0 days 01:00:00
225 0 days 01:00:00
101 0 days 01:00:00
123 0 days 01:00:00
116 0 days 01:00:00
329 0 days 01:00:00
95 0 days 01:00:00
168 0 days 01:00:00
129 0 days 01:00:00
49 0 days 01:00:00
389 0 days 01:00:00
182 0 days 01:00:00
219 0 days 01:00:00
80 0 days 01:00:00
1 0 days 01:00:00
170 0 days 01:00:00
162 0 days 01:00:00
198 0 days 01:00:00
402 0 days 01:00:00
331 0 days 01:00:00
160 0 days 01:00:00
38 0 days 01:00:00
320 0 days 01:00:00
46 0 days 01:00:00
24 0 days 01:00:00
72 0 days 01:00:00
143 0 days 01:00:00
253 0 days 01:00:00
254 0 days 01:00:00
401 0 days 01:00:00
261 0 days 01:00:00
258 0 days 01:00:00
200 0 days 01:00:00
251 0 days 01:00:00
193 0 days 01:00:00
50 0 days 01:00:00
58 0 days 01:00:00
336 0 days 01:00:00
136 0 days 01:00:00
68 0 days 01:00:00
391 0 days 01:00:00
180 0 days 01:00:00
25 0 days 01:00:00
63 0 days 01:00:00
137 0 days 01:00:00
28 0 days 01:00:00
244 0 days 01:00:00
234 0 days 01:00:00
181 0 days 01:00:00
100 0 days 01:00:00
135 0 days 01:00:00
3 0 days 01:00:00
31 0 days 01:00:00
248 0 days 01:00:00
110 0 days 01:00:00
330 0 days 01:00:00
246 0 days 01:00:00
194 0 days 01:00:00
149 0 days 01:00:00
183 0 days 01:00:00
166 0 days 01:00:00
202 0 days 01:00:00
102 0 days 01:00:00
111 0 days 01:00:00
332 0 days 01:00:00
171 0 days 01:00:00
319 0 days 01:00:00
152 0 days 01:00:00
138 0 days 01:00:00
140 0 days 01:00:00
76 0 days 01:00:00
115 0 days 01:00:00
155 0 days 01:00:00
243 0 days 01:00:00
56 0 days 01:00:00
204 0 days 01:00:00
158 0 days 01:00:00
73 0 days 01:00:00
210 0 days 01:00:00
232 0 days 01:00:00
333 0 days 01:00:00
18 0 days 01:00:00
75 0 days 01:00:00
81 0 days 01:00:00
30 0 days 01:00:00
67 0 days 01:00:00
153 0 days 01:00:00
70 0 days 01:00:00
216 0 days 01:00:00
86 0 days 01:00:00
327 0 days 01:00:00
259 0 days 01:00:00
45 0 days 01:00:00
15 0 days 01:00:00
141 0 days 01:00:00
44 0 days 01:00:00
39 0 days 01:00:00
257 0 days 01:00:00
121 0 days 01:00:00
90 0 days 01:00:00
226 0 days 01:00:00
215 0 days 01:00:00
54 0 days 01:00:00
205 0 days 01:00:00
256 0 days 01:00:00
130 0 days 01:00:00
118 0 days 01:00:00
199 0 days 01:00:00
250 0 days 01:00:00
29 0 days 01:00:00
209 0 days 01:00:00
203 0 days 01:00:00
37 0 days 01:00:00
148 0 days 01:00:00
145 0 days 01:00:00
43 0 days 01:00:00
144 0 days 01:00:00
196 0 days 01:00:00
26 0 days 01:00:00
48 0 days 01:00:00
42 0 days 01:00:00
163 0 days 01:00:00
147 0 days 01:00:00
83 0 days 01:00:00
106 0 days 01:00:00
328 0 days 01:00:00
109 0 days 01:00:00
229 0 days 01:00:00
217 0 days 01:00:00
146 0 days 01:00:00
8 0 days 01:00:00
223 0 days 01:00:00
326 0 days 01:00:00
134 0 days 01:00:00
201 0 days 01:00:00
184 0 days 01:00:00
228 0 days 01:00:00
237 0 days 01:00:00
195 0 days 01:00:00
127 0 days 01:00:00
176 0 days 01:00:00
197 0 days 01:00:00
211 0 days 01:00:00
65 0 days 01:00:00
188 0 days 01:00:00
322 0 days 01:00:00
64 0 days 01:00:00
97 0 days 01:00:00
89 0 days 01:00:00
126 0 days 01:00:00
112 0 days 01:00:00
230 0 days 01:00:00
128 0 days 01:00:00
177 0 days 01:00:00
179 0 days 01:00:00
161 0 days 01:00:00
239 0 days 01:00:00
55 0 days 01:00:00
165 0 days 01:00:00
220 0 days 01:00:00
231 0 days 01:00:00
9 0 days 01:00:00
151 0 days 01:00:00
185 0 days 01:00:00
150 0 days 01:00:00
88 0 days 01:00:00
19 0 days 01:00:00
186 0 days 01:00:00
236 0 days 01:00:00
174 0 days 01:00:00
175 0 days 01:00:00
235 0 days 01:00:00
85 0 days 01:00:00
53 0 days 01:00:00
133 0 days 01:00:00
13 0 days 01:00:00
51 0 days 01:00:00
47 0 days 01:00:00
159 0 days 01:00:00
154 0 days 01:00:00
35 0 days 01:00:00
190 0 days 01:00:00
323 0 days 01:00:00
255 0 days 01:00:00
91 0 days 01:00:00
189 0 days 01:00:00
87 0 days 01:00:00

In [28]:
max_diff

Timedelta('0 days 01:00:00')